# Generated by Django 5.0.6 on 2024-08-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_adminprocessorcontract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprocessorcontract',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
