# Generated by Django 5.0.6 on 2024-08-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_adminprocessorcontract_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprocessorcontract',
            name='contract_period_choice',
            field=models.CharField(choices=[('Days', 'Days'), ('Months', 'Months'), ('Year', 'Year')], default='Days', max_length=10),
        ),
        migrations.AddField(
            model_name='adminprocessorcontract',
            name='processor_entity_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adminprocessorcontract',
            name='contract_period',
            field=models.PositiveIntegerField(help_text='Warranty period'),
        ),
        migrations.AlterField(
            model_name='adminprocessorcontract',
            name='contract_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='adminprocessorcontract',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
