# Generated by Django 5.0.6 on 2024-08-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_adminprocessorcontract_contract_period_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprocessorcontract',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminprocessorcontract',
            name='secret_key',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
