# Generated by Django 5.0.6 on 2024-08-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_remove_adminprocessorcontract_required_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprocessorcontractdocuments',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='contracts/documents/'),
        ),
    ]
