# Generated by Django 5.0.6 on 2024-08-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_alter_adminprocessorcontractdocuments_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprocessorcontract',
            name='crop_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
