# Generated by Django 5.0.6 on 2024-08-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_adminprocessorcontract_crop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprocessorcontract',
            name='reason_for_rejection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminprocessorcontract',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Terminated', 'Terminated')], max_length=10),
        ),
    ]
