# Generated by Django 5.0.6 on 2024-08-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_adminprocessorcontract_reason_for_rejection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprocessorcontract',
            name='crop',
            field=models.CharField(choices=[('RICE', 'Rice'), ('WHEAT', 'Wheat'), ('PEANUT', 'Peanut'), ('BEANS', 'Beans')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adminprocessorcontract',
            name='status',
            field=models.CharField(choices=[('Contract Initiated', 'Contract Initiated'), ('Under Review', 'Under Review'), ('Active With Documentation Processing', 'Active With Documentation Processing'), ('Active With Documentation Completed', 'Active With Documentation Completed'), ('Completed', 'Completed'), ('Terminated', 'Terminated')], max_length=255),
        ),
    ]
