# Generated by Django 5.0.6 on 2024-08-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_alter_adminprocessorcontract_crop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprocessorcontractdocuments',
            name='document_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
