# Generated by Django 5.0.6 on 2024-08-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_rename_admincustomersignature_admincustomercontractsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprocessorcontract',
            name='left_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
