# Generated by Django 5.0.6 on 2024-09-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_admincustomercontract_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincustomercontract',
            name='left_amount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
