# Generated by Django 5.0.6 on 2024-09-08 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0021_remove_adminprocessorcontract_left_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContractCropDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(choices=[('RICE', 'Rice'), ('WHEAT', 'Wheat'), ('PEANUT', 'Peanut'), ('BEANS', 'Beans')], max_length=10)),
                ('crop_type', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_amount', models.PositiveBigIntegerField()),
                ('amount_unit', models.CharField(choices=[('LBS', 'LBS'), ('MT', 'MT')], max_length=10)),
                ('per_unit_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('left_amount', models.IntegerField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.admincustomercontract')),
            ],
        ),
    ]
