# Generated by Django 5.0.6 on 2024-09-08 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0023_alter_customercontractcropdetails_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admincustomercontract',
            name='amount_unit',
        ),
        migrations.RemoveField(
            model_name='admincustomercontract',
            name='contract_amount',
        ),
        migrations.RemoveField(
            model_name='admincustomercontract',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='admincustomercontract',
            name='crop_type',
        ),
        migrations.RemoveField(
            model_name='admincustomercontract',
            name='per_unit_rate',
        ),
    ]
