# Generated by Django 5.0.6 on 2024-09-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0026_remove_admincustomercontract_left_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropdetails',
            name='crop',
            field=models.CharField(blank=True, choices=[], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customercontractcropdetails',
            name='crop',
            field=models.CharField(blank=True, choices=[], max_length=255, null=True),
        ),
    ]
