# Generated by Django 5.0.6 on 2024-10-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0028_shipmentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitem',
            name='quickbooks_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
