# Generated by Django 5.0.6 on 2024-10-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0029_alter_shipmentitem_quickbooks_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitem',
            name='per_unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
