# Generated by Django 5.0.6 on 2024-11-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0030_alter_shipmentitem_per_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
