# Generated by Django 5.0 on 2024-04-11 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field', '0001_initial'),
        ('grower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NasdaqApiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_api', models.DateField(blank=True, null=True)),
                ('close_value_api', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntryFeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Modified Date')),
                ('crop', models.CharField(blank=True, max_length=200, null=True, verbose_name='Select Item')),
                ('contracted_payment_option', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contracted Payment Option')),
                ('contract_base_price', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contract Base Price / LBS')),
                ('sustainability_premium', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sustainability Premium')),
                ('quality_premium', models.CharField(blank=True, max_length=200, null=True, verbose_name='Quality Premium')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=200)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('grower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grower.grower', verbose_name='Select Grower')),
            ],
        ),
        migrations.CreateModel(
            name='GrowerPayee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grower_namee', models.CharField(blank=True, max_length=200, null=True)),
                ('grower_idd', models.CharField(blank=True, max_length=200, null=True)),
                ('field_namee', models.CharField(blank=True, max_length=200, null=True)),
                ('field_idd', models.CharField(blank=True, max_length=200, null=True)),
                ('crop', models.CharField(blank=True, max_length=200, null=True)),
                ('payee_entity_name', models.CharField(blank=True, max_length=200, null=True)),
                ('payee_tax_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payee_physical_address', models.TextField(blank=True, null=True)),
                ('payee_mailing_address', models.TextField(blank=True, null=True)),
                ('payee_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('payee_email', models.CharField(blank=True, max_length=200, null=True)),
                ('lien_holder_status', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_split_status', models.CharField(blank=True, max_length=200, null=True)),
                ('net_payee', models.CharField(blank=True, max_length=200, null=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field.field', verbose_name='Select Grower Field')),
                ('grower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grower.grower', verbose_name='Select Grower Payee')),
            ],
        ),
        migrations.CreateModel(
            name='GrowerPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Modified Date')),
                ('processor', models.IntegerField(blank=True, null=True, verbose_name='Select Processor')),
                ('grower_name', models.CharField(blank=True, max_length=250, null=True)),
                ('field_name', models.CharField(blank=True, max_length=250, null=True)),
                ('farm_name', models.CharField(blank=True, max_length=250, null=True)),
                ('level', models.CharField(blank=True, max_length=250, null=True)),
                ('field', models.IntegerField(blank=True, null=True, verbose_name='Select Field')),
                ('farm', models.IntegerField(blank=True, null=True, verbose_name='Select Farm')),
                ('crop', models.CharField(blank=True, max_length=200, null=True, verbose_name='Select Item')),
                ('variety', models.CharField(blank=True, max_length=200, null=True, verbose_name='Select Variety')),
                ('delivery_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Delivery Id')),
                ('delivery_date', models.CharField(blank=True, max_length=200, null=True, verbose_name='Delivery Date')),
                ('delivery_lbs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Delivery Lbs')),
                ('contract_base_price', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contract Base Price / LBS')),
                ('sustainability_premium', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sustainability Premium')),
                ('quality_premium', models.CharField(blank=True, max_length=200, null=True, verbose_name='Quality Premium')),
                ('total_price', models.CharField(blank=True, max_length=200, null=True, verbose_name='Total price')),
                ('delivered_value', models.CharField(blank=True, max_length=200, null=True, verbose_name='Delivered Value')),
                ('payment_due_date', models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment Due Date')),
                ('payment_amount', models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment Amount')),
                ('payment_date', models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment Date')),
                ('payment_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment Type')),
                ('payment_confirmation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment Confirmation')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=200)),
                ('total_price_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Total price Old')),
                ('delivered_value_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Delivered Value Old')),
                ('enteyfeeds', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='growerpayments.entryfeeds', verbose_name='EntryFeeds')),
                ('grower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grower.grower', verbose_name='Select Grower')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSplits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_payee_name', models.CharField(blank=True, max_length=200, null=True)),
                ('split_payee_tax_id', models.CharField(blank=True, max_length=200, null=True)),
                ('split_payee_physical_address', models.TextField(blank=True, null=True)),
                ('split_payee_mailing_address', models.TextField(blank=True, null=True)),
                ('split_payee_contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('split_payee_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('split_payee_email', models.CharField(blank=True, max_length=200, null=True)),
                ('split_payee_percent', models.CharField(blank=True, max_length=200, null=True)),
                ('split_payee_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lien or Split')),
                ('grower_payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='growerpayments.growerpayee')),
            ],
        ),
    ]
