# Generated by Django 5.0 on 2024-04-11 11:01

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('grower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(blank=True, choices=[('User', 'User'), ('Grower', 'Grower'), ('Farm', 'Farm'), ('Field', 'Field'), ('Storage', 'Storage'), ('FieldActivity', 'FieldActivity'), ('GrowerShipment', 'GrowerShipment'), ('ProcessorUser', 'ProcessorUser'), ('ClassingReport', 'ClassingReport'), ('ClassingListTier2', 'ClassingListTier2'), ('ProcessorUser2', 'ProcessorUser2'), ('LinkGrowerToProcessor', 'LinkGrowerToProcessor'), ('ProductionManagement', 'ProductionManagement'), ('ShipmentManagement', 'ShipmentManagement'), ('GrowerPayee', 'GrowerPayee')], max_length=250, null=True)),
                ('log_status', models.CharField(blank=True, choices=[('Added', 'Added'), ('Edited', 'Edited'), ('Password changed', 'Password changed'), ('Deleted', 'Deleted')], max_length=250, null=True)),
                ('log_idd', models.CharField(blank=True, max_length=250, null=True)),
                ('log_name', models.CharField(blank=True, max_length=250, null=True)),
                ('log_email', models.CharField(blank=True, max_length=250, null=True)),
                ('log_details', models.TextField(blank=True, null=True)),
                ('log_device', models.CharField(blank=True, choices=[('Web', 'Web'), ('App', 'App')], max_length=250, null=True)),
                ('action_by_userid', models.CharField(blank=True, max_length=250, null=True)),
                ('action_by_username', models.CharField(blank=True, max_length=250, null=True)),
                ('action_by_email', models.CharField(blank=True, max_length=250, null=True)),
                ('action_by_role', models.CharField(blank=True, max_length=250, null=True)),
                ('action_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. user_management', max_length=255)),
                ('display', models.CharField(help_text='e.g. User Management', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShowNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_to_show', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('msg', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('READ', 'READ'), ('UNREAD', 'UNREAD')], default='UNREAD', max_length=255, null=True)),
                ('redirect_url', models.TextField(blank=True, null=True)),
                ('added_data_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('grower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grower.grower')),
                ('permissions', models.ManyToManyField(to='accounts.permission')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Email', max_length=254)),
                ('username', models.CharField(help_text='Username', max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, help_text='First Name', max_length=150)),
                ('last_name', models.CharField(blank=True, help_text='Last Name', max_length=150)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('is_consultant', models.BooleanField(default=False)),
                ('is_processor', models.BooleanField(default=False)),
                ('is_processor2', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('password_raw', models.CharField(max_length=128, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('grower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grower.grower')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ManyToManyField(to='accounts.role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='SubSuperUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(help_text='ex: cconsultant@gmail.com', max_length=254, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
            ],
            options={
                'verbose_name': 'SubSuperUser',
                'verbose_name_plural': 'SubSuperUsers',
            },
        ),
    ]
