# Generated by Django 5.0 on 2024-05-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_processor3',
            field=models.BooleanField(default=False),
        ),
    ]
