# Generated by Django 5.0.6 on 2024-08-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_versionupdate_updated_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_distributor',
            field=models.BooleanField(default=False),
        ),
    ]
