# Generated by Django 5.0.6 on 2024-08-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_warehouse_user',
            field=models.BooleanField(default=False),
        ),
    ]
