# Generated by Django 5.0.6 on 2024-08-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_warehouse_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_warehouse_user',
            new_name='is_customer',
        ),
        migrations.AddField(
            model_name='user',
            name='is_warehouse_manager',
            field=models.BooleanField(default=False),
        ),
    ]
