# Generated by Django 5.0.6 on 2024-11-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processorwarehouseshipment',
            name='lot_number',
        ),
        migrations.RemoveField(
            model_name='warehousecustomershipment',
            name='lot_number',
        ),
        migrations.AddField(
            model_name='processorshipmentcrops',
            name='lot_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='warehouseshipmentcrops',
            name='lot_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
