# Generated by Django 5.0.6 on 2024-11-27 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0002_remove_processorwarehouseshipment_lot_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorshipmentlotnumbertracking',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouseManagement.processorshipmentcrops'),
        ),
        migrations.AddField(
            model_name='warehouseshipmentlotnumbertracking',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouseManagement.warehouseshipmentcrops'),
        ),
    ]
