# Generated by Django 5.0.6 on 2024-11-28 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0003_processorshipmentlotnumbertracking_crop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='per_unit_rate',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.FloatField(blank=True, max_length=255, null=True)),
                ('per_unit_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('desccription', models.TextField(blank=True, null=True)),
                ('item_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('purchse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseItem', to='warehouseManagement.purchase')),
            ],
        ),
    ]
