# Generated by Django 5.0.6 on 2024-12-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0004_remove_purchase_amount_remove_purchase_per_unit_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='available_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
