# Generated by Django 5.0.6 on 2024-12-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0005_customer_available_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='available_credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
