# Generated by Django 5.0.6 on 2025-02-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0008_alter_invoice_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to='qr_code_processor_shipment/'),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to='qr_code_warehouse_shipment/'),
        ),
    ]
