# Generated by Django 5.0 on 2024-04-11 11:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('field', '0001_initial'),
        ('grower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyyear', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Survey Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Survey End Date')),
            ],
            options={
                'verbose_name': 'Name Survey',
                'verbose_name_plural': 'Name Surveys',
            },
        ),
        migrations.CreateModel(
            name='TypeSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Type Survey',
                'verbose_name_plural': 'Type Surveys',
            },
        ),
        migrations.CreateModel(
            name='InputSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionscore', models.IntegerField(blank=True, null=True)),
                ('optionscore_ids', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field.field')),
                ('grower', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='grower.grower')),
                ('namesurvey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='growersurvey.namesurvey')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inputsurvey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='growersurvey.inputsurvey')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionname', models.TextField()),
                ('questiontotalscore', models.IntegerField(blank=True, null=True)),
                ('questionorder', models.IntegerField(blank=True, null=True)),
                ('selection_type', models.CharField(default='radio', max_length=255)),
                ('evidence_requird', models.BooleanField(default=False)),
                ('evidence_descr', models.TextField(blank=True, null=True)),
                ('namesurvey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growersurvey.namesurvey')),
            ],
        ),
        migrations.CreateModel(
            name='OptionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionname', models.CharField(max_length=255)),
                ('optionscore', models.IntegerField(blank=True, null=True)),
                ('questionsurvey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growersurvey.questionsurvey')),
            ],
        ),
        migrations.AddField(
            model_name='inputsurvey',
            name='questionsurvey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='growersurvey.questionsurvey'),
        ),
        migrations.CreateModel(
            name='SurveyCsvTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grower_idd', models.CharField(blank=True, max_length=255, null=True)),
                ('grower_namee', models.CharField(blank=True, max_length=255, null=True)),
                ('field_idd', models.CharField(blank=True, max_length=255, null=True)),
                ('field_namee', models.CharField(blank=True, max_length=255, null=True)),
                ('crop', models.CharField(blank=True, max_length=255, null=True)),
                ('farm_idd', models.CharField(blank=True, max_length=255, null=True)),
                ('farm_namee', models.CharField(blank=True, max_length=255, null=True)),
                ('survey_name', models.CharField(blank=True, max_length=255, null=True)),
                ('question_name', models.TextField(blank=True, null=True)),
                ('ans_name', models.TextField(blank=True, null=True)),
                ('ans_score', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.CharField(blank=True, max_length=255, null=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field.field')),
                ('grower', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='grower.grower')),
                ('namesurvey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='growersurvey.namesurvey')),
            ],
        ),
        migrations.CreateModel(
            name='SustainabilitySurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyscore', models.IntegerField(blank=True, null=True)),
                ('totalscore', models.IntegerField(blank=True, null=True)),
                ('sustainabilityscore', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field.field')),
                ('grower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grower.grower')),
                ('last_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='growersurvey.questionsurvey')),
                ('namesurvey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growersurvey.namesurvey')),
            ],
        ),
        migrations.AddField(
            model_name='namesurvey',
            name='typesurvey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growersurvey.typesurvey'),
        ),
    ]
