# Generated by Django 5.0 on 2024-04-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(help_text='Example: a, b, c etc.', max_length=1)),
                ('text', models.TextField(blank=True, help_text="Option's text", null=True)),
                ('points', models.IntegerField()),
                ('is_active', models.BooleanField(default=True, help_text='Enable/Disable Option')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Whole Farm Question', 'Whole Farm Question'), ('Enrolled Fields Question', 'Enrolled Fields Question')], max_length=200)),
                ('type', models.CharField(choices=[('single_select', 'Single Select'), ('multi_select', 'Multi Select')], max_length=200)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('max_points', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
