# Generated by Django 5.0.4 on 2024-05-20 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower', '0001_initial'),
        ('processor', '0011_alter_growershipment_qr_code'),
        ('processor2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkToProcessor2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grower.grower', verbose_name='Select grower')),
                ('processor1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processor.processor', verbose_name='Select processor')),
                ('processor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processor2.processor2', verbose_name='Select processor2')),
            ],
        ),
    ]
