# Generated by Django 5.0.6 on 2024-05-22 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0001_initial'),
        ('grower', '0001_initial'),
        ('processor', '0011_alter_growershipment_qr_code'),
        ('processor2', '0002_linktoprocessor2'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowerShipmentToProcessor2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_time', models.TimeField(auto_created=True, auto_now_add=True, verbose_name='Processed Time')),
                ('process_date', models.DateField(auto_created=True, auto_now_add=True, verbose_name='Processed Date')),
                ('date_time_location', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Location Date')),
                ('date_time', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Shipment Date')),
                ('crop', models.CharField(blank=True, max_length=200, null=True, verbose_name='Select Item')),
                ('variety', models.CharField(blank=True, max_length=200, null=True, verbose_name='Select Variety')),
                ('amount', models.CharField(blank=True, max_length=200, null=True, verbose_name='Amount')),
                ('amount2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Amount2')),
                ('sustainability_score', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sustainability Score')),
                ('echelon_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Echelon Id')),
                ('shipment_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Shipment Id')),
                ('process_amount', models.CharField(blank=True, max_length=200, null=True, verbose_name='Processed Amount')),
                ('sku', models.CharField(blank=True, max_length=200, null=True, verbose_name='SKU ID')),
                ('module_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Module Tag #')),
                ('unit_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Unit Type')),
                ('unit_type2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Unit Type2')),
                ('total_amount', models.CharField(blank=True, max_length=200, null=True, verbose_name='Total Amount')),
                ('received_amount', models.CharField(blank=True, max_length=200, null=True, verbose_name='Received Amount')),
                ('token_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Token Id')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Approval Date')),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('DISAPPROVED', 'DISAPPROVED'), ('', '')], default='', max_length=200)),
                ('reason_for_disapproval', models.CharField(blank=True, max_length=200, null=True, verbose_name='Reason For Disapproval')),
                ('moisture_level', models.CharField(blank=True, max_length=200, null=True, verbose_name='Moisture Level')),
                ('fancy_count', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fancy Count')),
                ('head_count', models.CharField(blank=True, max_length=200, null=True, verbose_name='Head Count')),
                ('bin_location_processor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bin Location at Processor')),
                ('processor2_idd', models.CharField(blank=True, max_length=200, null=True)),
                ('processor2_name', models.CharField(blank=True, max_length=250, null=True)),
                ('qr_code', models.FileField(blank=True, null=True, upload_to='qr_code/')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field.field', verbose_name='Select Field')),
                ('files', models.ManyToManyField(blank=True, related_name='growershipmentfile', to='processor.growershipmentfile')),
                ('grower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grower.grower', verbose_name='Select Grower')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processor.location', verbose_name='Select Location')),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processor2.processor2', verbose_name='Select Processor')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.storage', verbose_name='Select Storage')),
            ],
            options={
                'ordering': ('-date_time',),
            },
        ),
        migrations.CreateModel(
            name='Processor2Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Location2 Name')),
                ('upload_type', models.CharField(choices=[('shapefile', 'Shapefile'), ('coordinates', 'Coordinates')], max_length=11, verbose_name='Upload2 Type')),
                ('shapefile_id', models.FileField(blank=True, null=True, upload_to='processor2_shapefile', verbose_name='Shapefile ID2')),
                ('latitude', models.CharField(blank=True, max_length=200, null=True, verbose_name='Latitude2')),
                ('longitude', models.CharField(blank=True, max_length=200, null=True, verbose_name='Longitude2')),
                ('eschlon_id', models.CharField(blank=True, max_length=200, null=True)),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processor2.processor2', verbose_name='Select Processor2')),
            ],
        ),
    ]
