# Generated by Django 5.0.6 on 2024-05-23 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor2', '0003_growershipmenttoprocessor2_processor2location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growershipmenttoprocessor2',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processor2.processor2location', verbose_name='Select Location'),
        ),
        migrations.DeleteModel(
            name='LinkToProcessor2',
        ),
    ]
