# Generated by Django 5.0.6 on 2024-05-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor2', '0004_alter_growershipmenttoprocessor2_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4')], max_length=5, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='processor2',
            name='processor_type',
            field=models.ManyToManyField(blank=True, null=True, to='processor2.processortype'),
        ),
        migrations.DeleteModel(
            name='GrowerShipmentToProcessor2',
        ),
    ]
