# Generated by Django 5.0.6 on 2024-05-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor2', '0005_processortype_processor2_processor_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor2',
            name='processor_type',
            field=models.ManyToManyField(blank=True, to='processor2.processortype'),
        ),
    ]
