# Generated by Django 5.0.6 on 2024-05-24 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor2', '0006_alter_processor2_processor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkProcessorToProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_procesor', to='processor2.processor2')),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processor', to='processor2.processor2')),
            ],
        ),
    ]
