# Generated by Django 5.0.6 on 2024-05-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor2', '0008_linkprocessor1toprocessor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShipmentManagement',
        ),
    ]
