# Generated by Django 5.0.6 on 2024-05-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor2', '0010_shipmentmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentmanagement',
            name='reason_for_disapproval',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Reason For Disapproval'),
        ),
        migrations.AddField(
            model_name='shipmentmanagement',
            name='received_weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shipmentmanagement',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
