# Generated by Django 5.0.4 on 2024-05-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor2', '0011_shipmentmanagement_reason_for_disapproval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentmanagement',
            name='qr_code_processor',
            field=models.FileField(blank=True, null=True, upload_to='qr_code_processor/'),
        ),
    ]
