# Generated by Django 5.0.6 on 2024-06-13 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0015_remove_shipmentmanagement_files_and_more'),
        ('processor2', '0012_shipmentmanagement_qr_code_processor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processor_sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_type', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2')], max_length=5)),
                ('sku_id', models.CharField(max_length=100)),
                ('processor1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.processoruser')),
                ('processor2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor2.processoruser2')),
            ],
        ),
    ]
