# Generated by Django 5.0.6 on 2024-06-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor2', '0013_processor_sku'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Processor_sku',
        ),
    ]
