# Generated by Django 5.0.6 on 2024-06-13 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0015_remove_shipmentmanagement_files_and_more'),
        ('processor2', '0016_rename_processor1_id_processor_sku_processor1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor_sku',
            name='processor1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processor.processor'),
        ),
        migrations.AlterField(
            model_name='processor_sku',
            name='processor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processor2.processor2'),
        ),
    ]
