# Generated by Django 5.0.6 on 2024-06-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor2', '0017_alter_processor_sku_processor1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor_sku',
            name='processor_type',
            field=models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4')], max_length=5),
        ),
    ]
