# Generated by Django 5.0.6 on 2024-09-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor2', '0019_shipmentmanagement_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentmanagement',
            name='variety',
            field=models.CharField(choices=[], default='DG-263L', max_length=255),
        ),
        migrations.AlterField(
            model_name='shipmentmanagement',
            name='crop',
            field=models.CharField(choices=[], default='RICE', max_length=255),
        ),
    ]
