# Generated by Django 5.0.6 on 2024-10-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor2', '0020_shipmentmanagement_variety_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor2',
            name='main_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Main Email'),
        ),
    ]
