# Generated by Django 5.0.6 on 2024-10-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor2', '0021_processor2_main_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor2',
            name='quickbooks_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
