# Generated by Django 5.0.6 on 2024-10-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor2', '0022_processor2_quickbooks_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor2',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
