# Generated by Django 5.0 on 2024-05-03 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processor3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fein', models.CharField(blank=True, max_length=250, null=True, verbose_name='FEIN')),
                ('entity_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Entity Name')),
                ('billing_address', models.TextField(blank=True, null=True, verbose_name='Billing Address')),
                ('shipping_address', models.TextField(blank=True, null=True, verbose_name='Shipping Address')),
                ('main_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Main Number')),
                ('main_fax', models.CharField(blank=True, max_length=250, null=True, verbose_name='Main Fax')),
                ('website', models.TextField(blank=True, null=True, verbose_name='Website')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessorUser3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Contact Name')),
                ('contact_email', models.CharField(blank=True, max_length=250, null=True, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Contact Phone')),
                ('contact_fax', models.CharField(blank=True, max_length=250, null=True, verbose_name='Contact Fax')),
                ('p_password_raw', models.CharField(blank=True, max_length=250, null=True)),
                ('processor3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processor3.processor3', verbose_name='Select Processor3')),
            ],
        ),
    ]
