# Generated by Django 5.0.6 on 2024-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0004_alter_crop_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldupdated',
            name='crop',
            field=models.CharField(blank=True, choices=[], max_length=255, null=True),
        ),
    ]
