# Generated by Django 5.0.6 on 2024-09-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0007_rename_variety_cropvariety_variety_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='variety',
            field=models.CharField(blank=True, choices=[], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fieldupdated',
            name='variety',
            field=models.CharField(blank=True, choices=[], max_length=255, null=True),
        ),
    ]
