# Generated by Django 5.0 on 2024-04-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_file_shipmentmanagement_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentmanagement',
            name='processor2_idd',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipmentmanagement',
            name='processor_type',
            field=models.CharField(blank=True, choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('Buyer', 'Buyer')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='growershipment',
            name='sku',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SKU ID'),
        ),
        migrations.AlterField(
            model_name='shipmentmanagement',
            name='storage_bin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Storage Bin ID(SKU ID)'),
        ),
    ]
