# Generated by Django 5.0 on 2024-04-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_shipmentmanagement_processor2_idd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentmanagement',
            name='processor2_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
