# Generated by Django 5.0 on 2024-05-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0004_shipmentmanagement_processor2_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowerShipmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_grower_shipment/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='growershipment',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='growershipments', to='processor.growershipmentfile'),
        ),
    ]
