# Generated by Django 5.0 on 2024-05-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0005_growershipmentfile_growershipment_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
