# Generated by Django 5.0 on 2024-05-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0006_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growershipmentfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
