# Generated by Django 5.0 on 2024-05-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0007_alter_growershipmentfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='growershipment',
            name='lot_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='growershipment',
            name='processor2_idd',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='growershipment',
            name='processor2_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='growershipment',
            name='sender',
            field=models.CharField(choices=[('Grower', 'Grower'), ('Processor', 'Processor')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='growershipment',
            name='volume_shipped',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
