# Generated by Django 5.0 on 2024-05-11 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0008_growershipment_lot_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growershipment',
            name='lot_number',
        ),
        migrations.RemoveField(
            model_name='growershipment',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='growershipment',
            name='volume_shipped',
        ),
    ]
