# Generated by Django 5.0.4 on 2024-05-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0010_alter_growershipmentfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growershipment',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to='qr_code/'),
        ),
    ]
