# Generated by Django 5.0.6 on 2024-05-24 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0011_alter_growershipment_qr_code'),
        ('processor2', '0006_alter_processor2_processor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='processor_shipment_files', verbose_name='ProcessorShipment Id'),
        ),
        migrations.CreateModel(
            name='LinkProcessor1ToProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processor.processor')),
                ('processor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processor2.processor2')),
            ],
        ),
    ]
