# Generated by Django 5.0.6 on 2024-05-24 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0013_rename_processor_type_shipmentmanagement_receiver_processor_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentmanagement',
            name='production_management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processor.productionmanagement'),
        ),
    ]
