# Generated by Django 5.0.6 on 2024-05-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0014_shipmentmanagement_production_management'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentmanagement',
            name='files',
        ),
        migrations.RemoveField(
            model_name='shipmentmanagement',
            name='production_management',
        ),
        migrations.DeleteModel(
            name='LinkProcessor1ToProcessor',
        ),
        migrations.DeleteModel(
            name='ShipmentManagement',
        ),
    ]
