# Generated by Django 5.0.6 on 2024-10-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickbookstoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
