# Generated by Django 5.0.6 on 2024-10-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks_integration', '0002_alter_quickbookstoken_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbookstoken',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
