# Generated by Django 5.0 on 2024-04-11 11:01

import apps.core.validate
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(help_text='ex: cconsultant@gmail.com', max_length=254, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consultant',
                'verbose_name_plural': 'Consultants',
            },
        ),
        migrations.CreateModel(
            name='Grower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ex: Fred Farmer', max_length=255)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(help_text='ex: ffarmer@gmail.com', max_length=254, unique=True)),
                ('physical_address1', models.CharField(blank=True, max_length=255, null=True)),
                ('physical_address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city1', models.CharField(blank=True, max_length=255, null=True)),
                ('state1', models.CharField(blank=True, max_length=200, null=True)),
                ('zip_code1', models.BigIntegerField(blank=True, null=True, validators=[apps.core.validate.validate_zipcode])),
                ('mailing_address1', models.CharField(blank=True, max_length=255, null=True)),
                ('mailing_address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city2', models.CharField(blank=True, max_length=255, null=True)),
                ('state2', models.CharField(blank=True, max_length=200, null=True)),
                ('zip_code2', models.BigIntegerField(blank=True, null=True, validators=[apps.core.validate.validate_zipcode])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('consultant', models.ManyToManyField(to='grower.consultant')),
            ],
            options={
                'verbose_name': 'Grower',
                'verbose_name_plural': 'Growers',
            },
        ),
        migrations.CreateModel(
            name='GrowerChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('checkstatus', models.BooleanField(blank=True, null=True)),
                ('date_checked', models.DateField(auto_now_add=True)),
                ('module', models.CharField(max_length=200)),
                ('grower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grower.grower')),
            ],
        ),
    ]
