# Generated by Django 5.0 on 2024-04-11 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='survey_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveytype', verbose_name='Survey Type'),
        ),
        migrations.AddField(
            model_name='document',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='gallery.gallery'),
        ),
    ]
