# Generated by Django 5.0 on 2024-04-11 11:01

import apps.core.validate
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvToFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='CSV')),
            ],
        ),
        migrations.CreateModel(
            name='FarmGrouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grouping_criteria', models.CharField(choices=[('farm', 'Farm'), ('grower', 'Grower'), ('crop', 'Crop'), ('variety', 'Variety'), ('crop_tech', 'Crop Tech'), ('burndown_chemical', 'Burndown Chemical'), ('preemergence_chemical', 'Preemergence Chemical'), ('stand_count', 'Stand Count'), ('fungicide_micronutrients', 'Fungicide Micronutrients'), ('insecticide_application', 'Insecticide Application'), ('litter', 'Litter'), ('pre_fert_product', 'Pre Fert Product'), ('early_post_fert_product', 'Early Post Fert Product'), ('foliar_fert_app_product', 'Foliar Fert App Product'), ('pre_flood_fert_product', 'Pre Flood Fert Product'), ('post_flood_midseason_fert_product', 'Post Flood Midseason Fert Product'), ('post_flood_midseason_fert_product2', 'Post Flood Midseason Fert Product2'), ('post_flood_midseason_fert_product3', 'Post Flood Midseason Fert Product3'), ('boot_fertilizer_product', 'Boot Fertilizer Product'), ('water_source', 'Water Source'), ('measured_water_use', 'Measured Water Use'), ('field_design_and_use_of_plastic_pipe', 'Field Design And Use Of Plastic Pipe'), ('previous_crop', 'Previous Crop'), ('straw_burnt_or_residue_removed', 'Straw Burnt Or Residue Removed'), ('straw_residue_tillage_and_cover_crop_management', 'Straw Residue Tillage And Cover Crop Management'), ('tillage_equipment_and_passes_or_fuel_usage_for_tillage', 'Tillage Equipment And Passes Or Fuel Usage For Tillage')], max_length=255, verbose_name='Farm Grouping Criteria')),
            ],
            options={
                'verbose_name': 'Farm Grouping',
                'verbose_name_plural': 'Farm Groupings',
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('cultivation_year', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cultivation Year')),
                ('area', models.FloatField(blank=True, null=True)),
                ('land_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Land Type')),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('county', models.CharField(blank=True, max_length=200, null=True)),
                ('village', models.CharField(blank=True, max_length=200, null=True)),
                ('town', models.CharField(blank=True, max_length=200, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('zipcode', models.BigIntegerField(blank=True, null=True, validators=[apps.core.validate.validate_zipcode], verbose_name='Zip Code')),
                ('nutrien_account_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('grower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grower.grower')),
            ],
            options={
                'verbose_name': 'Farm',
                'verbose_name_plural': 'Farms',
            },
        ),
    ]
