# Generated by Django 5.0.6 on 2024-09-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagefeed',
            name='status',
            field=models.CharField(blank=True, choices=[('quantity_in', 'Quantity In'), ('quantity_edit', 'Quantity Edit')], max_length=200, null=True, verbose_name='Quantity Status'),
        ),
    ]
