"""Field Coloum Choices for CSV import functionality"""
class FieldColoumChoices:
    field_coloum = ('farm','name','batch_id','acreage','fsa_farm_number','fsa_tract_number','fsa_field_number',
    'latitude','longitude','crop','variety','yield_per_acre','total_yield','crop_tech','burndown_chemical',
    'burndown_chemical_date','plant_date','preemergence_chemical','preemergence_chemical_date','stand_count',
    'emergence_date','post_emergence_chemical_1','post_emergence_chemical_1_date','post_emergence_chemical_2',
    'post_emergence_chemical_2_date','post_emergence_chemical_3','post_emergence_chemical_3_date',
    'post_emergence_chemical_4','post_emergence_chemical_4_date','flood_date','awd_drydown_date',
    'fungicide_micronutrients','fungicide_micronutrients_date','insecticide_application',
    'insecticide_application_date','drain_date','sodium_chlorate_date','harvest_date','soil_sample_date',
    'litter','pre_fert_rate','pre_fert_product','early_post_fert_rate','early_post_fert_product',
    'early_post_fert_date','foliar_fert_app_rate','foliar_fert_app_product','foliar_fert_app_date',
    'pre_flood_fert_rate','pre_flood_fert_product','pre_flood_fert_date','post_flood_midseason_fert_rate',
    'post_flood_midseason_fert_product','post_flood_midseason_fert_date','post_flood_midseason_fert_rate2',
    'post_flood_midseason_fert_product2','post_flood_midseason_fert_date2','post_flood_midseason_fert_rate3',
    'post_flood_midseason_fert_product3','post_flood_midseason_fert_date3','boot_fertilizer_rate',
    'boot_fertilizer_product','boot_fertilizer_date','total_n_applied_lbs_ac','flow_meter_beginning_reading',
    'flow_meter_multiplier','flow_meter_end_reading','water_source','total_n_applied','measured_water_use',
    'field_design_and_use_of_plastic_pipe','soil_clay_percentage','previous_crop','straw_burnt_or_residue_removed',
    'straw_residue_tillage_and_cover_crop_management','tillage_equipment_and_passes_or_fuel_usage_for_tillage',
    'water_saving','co2_equivalents_reduced')