# Generated by Django 5.0 on 2024-04-11 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grower', '0001_initial'),
        ('processor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessorMsgboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_with', models.CharField(blank=True, choices=[('Grower-Consultant', 'Grower-Consultant'), ('Grower-Processor', 'Grower-Processor'), ('Grower-Admin', 'Grower-Admin')], default='Grower-Processor', max_length=200, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grower.consultant')),
                ('grower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grower.grower')),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processor.processor')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_is', models.CharField(blank=True, max_length=250, null=True)),
                ('sender_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='Grower or ProcessorUser ID')),
                ('sender_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Grower or ProcessorUser Name')),
                ('receiver_is', models.CharField(blank=True, max_length=250, null=True)),
                ('receiver_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='Grower or Processor ID')),
                ('receiver_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Grower or Processor Name')),
                ('msg', models.TextField(blank=True, null=True)),
                ('msg_date', models.DateField(auto_now_add=True)),
                ('msg_time', models.TimeField(auto_now_add=True)),
                ('read_status', models.CharField(blank=True, choices=[('READ', 'READ'), ('UNREAD', 'UNREAD')], max_length=250, null=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.processormsgboard')),
            ],
        ),
    ]
